base_url = "https://dcariotti.me"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true

[extra]
name = "Santo Cariotti"
description = "Computer Programmer ‚å®Ô∏èü§ñ"
avatar = "/avatar.jpg"
social_git = "http://git.dcariotti.me"
social_github = "boozec"
social_gitlab = "boozec"
social_instagram = "arcticsanto"
social_linkedin = "santocariotti"
social_mastodon = "hachyderm.io/@sa"
